Modul2Test_Branislav_Jovanovic/Models/Clanak.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Modul2Test_Branislav_Jovanovic.Models
{
    public class Clanak
    {
        public int Id { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 1)]
        public string Naslov { get; set; }
        [Required]
        [StringLength(1024, MinimumLength = 4)]
        public string Tekst { get; set; }
        [Required]
        [StringLength(20, MinimumLength = 1)]
        public string Autor { get; set; }
        public Kategorija Kategorija { get; set; }

    }
}

Modul2Test_Branislav_Jovanovic/Models/Kategorija.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Modul2Test_Branislav_Jovanovic.Models
{
    public class Kategorija
    {
        public int Id { get; set; }
        [Required]
        [StringLength(20, MinimumLength = 2)]
        public string Naziv { get; set; }
        [Required]
        [StringLength(40, MinimumLength = 4)]
        public string Opis { get; set; }
    }
}

Modul2Test_Branislav_Jovanovic/ViewModels/ClanakKategorijaViewModel.cs
using Modul2Test_Branislav_Jovanovic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Modul2Test_Branislav_Jovanovic.ViewModels
{
    public class ClanakKategorijaViewModel
    {
        public Clanak Clanak { get; set; }
        public List<Clanak> Clanci { get; set; }
        public List<Kategorija> Kategorije { get; set; }
    }
}

Modul2Test_Branislav_Jovanovic/Controllers/ClanakController.cs
using Modul2Test_Branislav_Jovanovic.Models;
using Modul2Test_Branislav_Jovanovic.Repository;
using Modul2Test_Branislav_Jovanovic.Repository.Interfaces;
using Modul2Test_Branislav_Jovanovic.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Modul2Test_Branislav_Jovanovic.Controllers
{
    public class ClanakController : Controller
    {
        private IClanakRepository clanakRepo = new ClanakRepo();
        private IKategorijaRepository kategorijaRepo = new KategorijaRepo();
        // GET: Clanak
        public ActionResult Index()
        {
            ClanakKategorijaViewModel clanakKategorije = new ClanakKategorijaViewModel
            {
                Kategorije = kategorijaRepo.GetAll().ToList(),
                Clanci = clanakRepo.GetAll().ToList()
            };

            return View(clanakKategorije);
        }

        [HttpPost]
        public ActionResult Create(Clanak clanak)
        {
            ModelState.Values.ElementAt(4).Errors.Clear();      // Brisanje gresaka napravljenih tokom dodatne serverske validacije za klasu Kategorija
            ModelState.Values.ElementAt(5).Errors.Clear();
            if (!ModelState.IsValid)
            {
                ClanakKategorijaViewModel clanakKategorije = new ClanakKategorijaViewModel
                {
                    Clanak = clanak,
                    Kategorije = kategorijaRepo.GetAll().ToList(),
                    Clanci = clanakRepo.GetAll().ToList()
                };
                return View("Index", clanakKategorije);
            }

            if (clanakRepo.Create(clanak))
            {
                return RedirectToAction("Index");
            }

            return View("Error");
        }

        public ActionResult Delete(int id)
        {
            try
            {
                clanakRepo.Delete(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }

        public ActionResult Edit(int id)
        {
            ClanakKategorijaViewModel clanakKategorije = new ClanakKategorijaViewModel
            {
                Kategorije = kategorijaRepo.GetAll().ToList(),
                Clanak = clanakRepo.GetById(id)
            };

            return View(clanakKategorije);
        }

        [HttpPost]
        public ActionResult Edit(int id, Clanak clanak)
        {
            if (!ModelState.IsValid)
            {
                ClanakKategorijaViewModel clanakKategorije = new ClanakKategorijaViewModel
                {
                    Clanak = clanak,
                    Kategorije = kategorijaRepo.GetAll().ToList(),
                    Clanci = clanakRepo.GetAll().ToList()
                };
                return View(clanakKategorije);
            }

            try
            {
                clanakRepo.Update(clanak);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }

        }
    }
}

Modul2Test_Branislav_Jovanovic/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Modul2Test_Branislav_Jovanovic.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Modul2Test_Branislav_Jovanovic/Controllers/KategorijaController.cs
using Modul2Test_Branislav_Jovanovic.Models;
using Modul2Test_Branislav_Jovanovic.Repository;
using Modul2Test_Branislav_Jovanovic.Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Modul2Test_Branislav_Jovanovic.Controllers
{
    public class KategorijaController : Controller
    {
        private IKategorijaRepository kategorijaRepo = new KategorijaRepo();
        // GET: Kategorija
        public ActionResult Index()
        {
            var kategorije = kategorijaRepo.GetAll();

            return View(kategorije);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Kategorija kategorija)
        {
            if (!ModelState.IsValid)
            {
                return View(kategorija);
            }
            if (kategorijaRepo.Create(kategorija))
            {
                return RedirectToAction("Index");
            }

            return View("Error");
        }

        public ActionResult Delete(int id)
        {
            try
            {
                kategorijaRepo.Delete(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }

        public ActionResult Edit(int id)
        {
            Kategorija kategorija = new Kategorija();
            kategorija = kategorijaRepo.GetById(id);

            return View(kategorija);
        }

        [HttpPost]
        public ActionResult Edit(int id, Kategorija kategorija)
        {
            try
            {
                kategorijaRepo.Update(kategorija);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }
    }
}

Modul2Test_Branislav_Jovanovic/Views/Clanak/Edit.cshtml
@model Modul2Test_Branislav_Jovanovic.ViewModels.ClanakKategorijaViewModel

@{
    ViewBag.Title = "Izmena Članka";
}

@section Scripts {
    @Scripts.Render("~/Scripts/clanak - validation.js")
}

<h2>Izmena Članka</h2>


@using (Html.BeginForm("Edit", "Clanak", FormMethod.Post, new { onsubmit = "return isFormValid(this)" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(model => model.Clanak.Id)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Clanak.Naslov, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Clanak.Naslov, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Clanak.Naslov, "", new { @class = "text-danger" })
                <span id="spnaslov" style="color:red"></span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Clanak.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Clanak.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Clanak.Autor, "", new { @class = "text-danger" })
                <span id="spautor" style="color:red"></span>
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.DropDownListFor(model => model.Clanak.Kategorija.Id,
                                                      new SelectList(@Model.Kategorije, "Id", "Naziv"),
                                                      "Izaberi Kategoriju")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Clanak.Tekst, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="Clanak.Tekst" cols="50" rows="5">@Model.Clanak.Tekst</textarea>
                @Html.ValidationMessageFor(model => model.Clanak.Tekst, "", new { @class = "text-danger" })
                <span id="sptekst" style="color:red"></span>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Posalji" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Modul2Test_Branislav_Jovanovic/Views/Clanak/Index.cshtml
@model Modul2Test_Branislav_Jovanovic.ViewModels.ClanakKategorijaViewModel

@{
    ViewBag.Title = "Članci";
}

@section Scripts {
    @Scripts.Render("~/Scripts/clanak - validation.js")
}

<h2>Članci</h2>

@using (Html.BeginForm("Create", "Clanak", FormMethod.Post, new { onsubmit = "return isFormValid(this)" }))
{
    @Html.AntiForgeryToken()
    <hr />
    <div class="form-horizontal">
        <h4>Dodaj nov članak</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Clanak.Naslov, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Clanak.Naslov, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Clanak.Naslov, "", new { @class = "text-danger" })
                <span id="spnaslov" style="color:red"></span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Clanak.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Clanak.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Clanak.Autor, "", new { @class = "text-danger" })
                <span id="spautor" style="color:red"></span>
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.DropDownListFor(model => model.Clanak.Kategorija.Id,
                                                           new SelectList(@Model.Kategorije, "Id", "Naziv"),
                                                           "Izaberi Kategoriju")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Clanak.Tekst, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="Clanak.Tekst" id="Clanak_Tekst" cols="40" rows="5"></textarea>
                @Html.ValidationMessageFor(model => model.Clanak.Tekst, "", new { @class = "text-danger" })
                <span id="sptekst" style="color:red"></span>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Posalji" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Clanak.Naslov)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Clanak.Autor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Clanak.Tekst)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Clanak.Kategorija)
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model.Clanci)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naslov)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tekst)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kategorija.Naziv)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Modul2Test_Branislav_Jovanovic/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Modul2Test_Branislav_Jovanovic/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Modul2Test_Branislav_Jovanovic/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>NOVINE</h1>
    <p class="lead">Napraviti ASP.NET MVC aplikaciju za objavljivanje novinskih članaka.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Članci</h2>
        <p>
        </p>
        <p><a class="btn btn-default" href="/Clanak">Pregled &raquo;</a></p>
    </div>
    <div class="col-md-6">
        <h2>Kategorije</h2>
        <p></p>
        <p><a class="btn btn-default" href="/Kategorija">Pregled &raquo;</a></p>
    </div>
</div>

Modul2Test_Branislav_Jovanovic/Views/Kategorija/Create.cshtml
@model Modul2Test_Branislav_Jovanovic.Models.Kategorija

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kategorija</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Modul2Test_Branislav_Jovanovic/Views/Kategorija/Edit.cshtml
@model Modul2Test_Branislav_Jovanovic.Models.Kategorija

@{
    ViewBag.Title = "Izmena Kategorije";
}

<h2>Izmena Kategorije</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Modul2Test_Branislav_Jovanovic/Views/Kategorija/Index.cshtml
@model IEnumerable<Modul2Test_Branislav_Jovanovic.Models.Kategorija>

@{
    ViewBag.Title = "Kategorije";
}

<h2>Kategorije</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Opis)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Opis)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Modul2Test_Branislav_Jovanovic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Novine", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Članci", "Index", "Clanak")</li>
                    <li>@Html.ActionLink("Kategorije", "Index", "Kategorija")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>